apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: cache
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: gcs-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcs-cache
spec:
  selector:
    matchLabels:
      app: gcs-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: gcs-cache
    spec:
      containers:
      - name: gcsproxy
        image: docker.io/rootfs/gcsproxy:latest
        volumeMounts:
        - name: json-key
          mountPath: /cfg
        command:
          - "/usr/bin/gcsproxy"
        args:
          - "-p"
          - ":8888"
          - "-c"
          - "/cfg/gcs.json" # must match configmap 
          - "-v"
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-conf
          mountPath: /cfg
        command:
          - "nginx"
        args:
          - "-c"
          - "/cfg/nginx-gcs.conf"
      volumes:
        - name: json-key
          configMap:
            name: gcs-key
        - name: nginx-conf
          configMap:
            name: nginx-conf
        
